# Generated by Django 5.1.1 on 2024-10-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqmodel',
            name='answer',
            field=models.TextField(verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='question',
            field=models.TextField(verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='faqmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='experience_description',
            field=models.TextField(verbose_name='Experience description'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='position',
            field=models.CharField(max_length=64, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
