# Generated by Django 5.1.1 on 2024-10-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usermodel_groups_usermodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_permissions',
        ),
    ]
