# Generated by Django 5.1.1 on 2024-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='problemmodel',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
